services:
  - type: web
    name: yomu-gateway
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GATEWAY_SHARED_SECRET
        sync: false
      - key: CORE_API_URL
        value: https://yomu-core-api.onrender.com
      - key: GAMIFICATION_ENGINE_URL
        value: https://yomu-gamification-engine.onrender.com
      - key: YOMU_WEB_URL
        sync: false
